### ISSUE TITLE
When interrupting Gitlab-CI Job, cancel Jenkins job

### ISSUE THREAD

**Issue by wixyvir** [pmsipilot/jenklab-ci#11]
Currently, when I stop a Gitlab-ci Job using jenklab-ci docker image, the matching Jenkins job is not interrupted.

It would be nice if it could be interrupted as well.

**Comment by jubianchi** [comment]
Yes, it is indeed a good idea.

I think we should experiment and see if we receive the correct signals. If yes, we could then send an API call to jenkins to stop the current job.

Should be easy to implement if Gitlab sends us the signal.
